### ISSUE TITLE
Problem setting TELR environment

### ISSUE THREAD

**Issue by elcortegano** [bergmanlab/TELR#2]
Hi, I am trying to install TELR, but after following [installation steps](https://github.com/bergmanlab/TELR/blob/master/docs/01_Installation.md), the following error when running TELR for the test dataset:

```
Traceback (most recent call last):
  File "../telr.py", line 8, in <module>
    from TELR_input import get_args, parse_input
  File "/localdisk/home/elopezc/telr/TELR_input.py", line 6, in <module>
    from Bio import SeqIO
ModuleNotFoundError: No module named 'Bio'
```

I am confused about the source of this error, since it is my understanding that all dependencies should be available in the newly created conda environment (`TELR_env` is activated in my case).

**Comment by elcortegano** [comment]
Just in case it helps, I found it might be a problem with permissions (this problem arose in a cluster, but I can run the software on my personal computer).

On the cluster, I can make steps forward by installing missing python libraries using the `--user` option, e.g.:

    python3 -m pip install --user Bio

But it will reach a point where nothing more can be done, because there are no permissions to run `ngmlr`. Running the test as:

     ../telr.py -o test_output -i reads.fasta -r ref_38kb.fasta -l library.fasta

Will return the following:

    Successfully created the directory /localdisk/home/elopezc/telr/test/test_output 
    Successfully created the directory /localdisk/home/elopezc/telr/test/test_output/intermediate_files 
    [Errno 13] Permission denied: 'ngmlr'
    Read alignment (ngmlr) failed, check input reads, exiting...

Is this an expected problem? should this environment and script only be run in a system with full permissions? Thank you.

**Comment by shunhuahan** [comment]
- Hi @elcortegano thanks for bringing up issues regarding to TELR env installation. One of the reasons we implement conda env installation in TELR is to free users from having to install programs manually, which sometimes require root permission. You should be able to use all softwares included in `TELR_env` as long as the conda env is installed and activated correctly. In another word, you don't need root permission in the system in order to run TELR.
- Can you check if the following lines are present in the `~/.bashrc` profile?
```
export PATH=$PATH:$HOME/miniconda/bin

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/sh60271/miniconda/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/sh60271/miniconda/etc/profile.d/conda.sh" ]; then
        . "/home/sh60271/miniconda/etc/profile.d/conda.sh"
    else
        export PATH="/home/sh60271/miniconda/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
```
- Did you get error messages when you use `conda activate TELR_env` or `conda update conda`?

**Comment by shunhuahan** [comment]
@elcortegano Good to hear that you were able to install TELR on different clusters. Closing this issue for now. Let me know if you encounter other install/env related issues.
