### ISSUE TITLE
Multi-Sample TEs Calling 

### ISSUE THREAD

**Issue by Anees-caas** [bergmanlab/TELR#39]
Hi, is there and update or the current version is working with multiple samples?

**Comment by cbergman** [comment]
Hi @Anees-caas. Currently, we are not working on a multi-sample version of TELR. You could try running TELR in single-sample mode and merging results with SURVIVOR: https://github.com/fritzsedlazeck/SURVIVOR.

**Comment by Anees-caas** [comment]
Thank you for this amazing tool! I am running single files, and it’s working. Both the survivor and swimmer merge are functioning with the VCF files from the TELR output.
